apiVersion: apps/v1
kind: Deployment
metadata:
  name: loans-deployment
  labels:
    app: loans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loans
  template:
    metadata: 
      labels:
        app: loans
    spec: 
      containers:
        - name: loans
          image: miguelmazo/loans
          ports:
          - containerPort: 8090
          env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: SPRING_PROFILES_ACTIVE
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: SPRING_CONFIG_IMPORT
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE